# Generated by Django 5.0.1 on 2024-01-10 16:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=30)),
                ("date", models.DateField()),
                (
                    "start_time",
                    models.TimeField(
                        choices=[
                            (datetime.time(18, 0), "18:00"),
                            (datetime.time(18, 30), "18:30"),
                            (datetime.time(19, 0), "19:00"),
                            (datetime.time(19, 30), "19:30"),
                            (datetime.time(20, 0), "20:00"),
                            (datetime.time(20, 30), "20:30"),
                            (datetime.time(21, 0), "21:00"),
                            (datetime.time(21, 30), "21:30"),
                        ],
                        default=datetime.time(18, 0),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
    ]
