# Generated by Django 5.0.1 on 2024-01-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="num_people",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of people attending"
            ),
        ),
    ]
